#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace Ops.Plugins.Model
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class CrmServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public CrmServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Ops.Plugins.Model.Opportunity"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Ops.Plugins.Model.Opportunity> OpportunitySet
		{
			get
			{
				return this.CreateQuery<Ops.Plugins.Model.Opportunity>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Ops.Plugins.Model.PluginAssembly"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Ops.Plugins.Model.PluginAssembly> PluginAssemblySet
		{
			get
			{
				return this.CreateQuery<Ops.Plugins.Model.PluginAssembly>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Ops.Plugins.Model.PluginType"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Ops.Plugins.Model.PluginType> PluginTypeSet
		{
			get
			{
				return this.CreateQuery<Ops.Plugins.Model.PluginType>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Ops.Plugins.Model.SdkMessage"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Ops.Plugins.Model.SdkMessage> SdkMessageSet
		{
			get
			{
				return this.CreateQuery<Ops.Plugins.Model.SdkMessage>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Ops.Plugins.Model.SdkMessageFilter"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Ops.Plugins.Model.SdkMessageFilter> SdkMessageFilterSet
		{
			get
			{
				return this.CreateQuery<Ops.Plugins.Model.SdkMessageFilter>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Ops.Plugins.Model.SdkMessageProcessingStep"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Ops.Plugins.Model.SdkMessageProcessingStep> SdkMessageProcessingStepSet
		{
			get
			{
				return this.CreateQuery<Ops.Plugins.Model.SdkMessageProcessingStep>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Ops.Plugins.Model.SdkMessageProcessingStepImage"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Ops.Plugins.Model.SdkMessageProcessingStepImage> SdkMessageProcessingStepImageSet
		{
			get
			{
				return this.CreateQuery<Ops.Plugins.Model.SdkMessageProcessingStepImage>();
			}
		}
	}
}
#pragma warning restore CS1591
