#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ops.Plugins.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum ops_industrytype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consult = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HR = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SaaS = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Client = 4,
	}
}
#pragma warning restore CS1591
